# Generated by Django 2.1.3 on 2018-11-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('avisos', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.AlterModelTable(
            name='interacao',
            table='interacao',
        ),
    ]
