# Generated by Django 2.1.3 on 2018-11-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181125_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=100)),
                ('datahora', models.DateTimeField(auto_now=True)),
                ('saida', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'comando_cache',
            },
        ),
    ]
