# Generated by Django 2.1.3 on 2018-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comandocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('papel', models.CharField(max_length=100)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_stop', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_tprofit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('situacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carteira',
            },
        ),
    ]
