# Generated by Django 2.1.3 on 2018-12-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carteira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'papel',
            },
        ),
    ]
