# Generated by Django 2.1.3 on 2018-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='papel',
            name='datahora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
