# Generated by Django 2.1.3 on 2018-12-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_papel_datahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='usuario_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
