# Generated by Django 2.1.3 on 2018-12-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
