# Generated by Django 2.1.3 on 2019-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_grupo_autorizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('usuario_id', models.CharField(max_length=100)),
                ('datahora', models.DateTimeField()),
                ('situacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'alarme',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chatid', models.CharField(max_length=100)),
                ('datahora', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'feriado',
            },
        ),
    ]
