# Generated by Django 2.1.3 on 2019-02-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alarme_blacklist_feriado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('usuario_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarioChat',
            },
        ),
    ]
