# Generated by Django 2.1.3 on 2019-02-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuariochat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='chatid',
            new_name='usuarioid',
        ),
    ]
