# Generated by Django 3.2.5 on 2021-08-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_carteira_direcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='papel',
            name='valor_maxima',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='papel',
            name='valor_minima',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
